#!/bin/bash

# GitHub Token Fix Script
# This script helps you generate and configure a new GitHub token

echo "========================================"
echo "   GitHub Token Fix"
echo "   IT Services Freetown"
echo "========================================"
echo ""
echo "❌ Current Issue:"
echo "   Your GitHub token has expired or is invalid."
echo "   Error: 401 Unauthorized - Bad credentials"
echo ""
echo "This affects:"
echo "   - Blog posts (GitHub Issues storage)"
echo "   - Today's Offer popup (GitHub Gist storage)"
echo "   - Comments system"
echo ""
echo "========================================"
echo "   How to Fix (5 minutes)"
echo "========================================"
echo ""
echo "Step 1: Generate New Token"
echo "──────────────────────────"
echo "1. Open this URL in your browser:"
echo "   https://github.com/settings/tokens/new"
echo ""
echo "2. Fill in the form:"
echo "   - Note: 'IT Services Blog & Offer Token'"
echo "   - Expiration: '90 days' or 'No expiration'"
echo ""
echo "3. Select these scopes (permissions):"
echo "   ✅ repo (Full control of private repositories)"
echo "   ✅ gist (Create gists)"
echo "   ✅ public_repo (Access public repositories)"
echo ""
echo "4. Click 'Generate token'"
echo ""
echo "5. COPY the token immediately (you won't see it again!)"
echo "   It looks like: ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
echo ""
echo "──────────────────────────"
echo "Step 2: Update .env.local"
echo "──────────────────────────"
echo ""
echo "Replace these lines in .env.local with your new token:"
echo ""
echo "NEXT_PUBLIC_GITHUB_TOKEN=YOUR_NEW_TOKEN_HERE"
echo "GITHUB_TOKEN=YOUR_NEW_TOKEN_HERE"
echo "GITHUB_ACCESS_TOKEN=YOUR_NEW_TOKEN_HERE"
echo ""
echo "──────────────────────────"
echo "Step 3: Restart Server"
echo "──────────────────────────"
echo ""
echo "1. Stop the dev server (Ctrl+C)"
echo "2. Start it again: npm run dev"
echo ""
echo "========================================"
echo ""
echo "Or use this quick command to update:"
echo ""
echo "  nano .env.local"
echo ""
echo "Then update all three token values and save (Ctrl+X, Y, Enter)"
echo ""
echo "========================================"
echo "   Need Help?"
echo "========================================"
echo ""
echo "If you see any errors after updating:"
echo "1. Make sure token starts with 'ghp_'"
echo "2. Make sure you selected 'repo' and 'gist' scopes"
echo "3. Make sure there are no spaces in the token"
echo "4. Restart the server after updating"
echo ""
echo "========================================"
