#!/bin/bash

# Blog Post Publisher
# This script helps you publish blog posts to your site

echo "======================================"
echo "   Blog Post Publisher"
echo "   IT Services Freetown"
echo "======================================"
echo ""

# Check if the blog post file exists
BLOG_FILE="blog-posts/best-laptops-freetown-2025.md"

if [ ! -f "$BLOG_FILE" ]; then
    echo "❌ Error: Blog post file not found!"
    exit 1
fi

echo "✅ Blog post file found: $BLOG_FILE"
echo ""
echo "📝 Blog Post Preview:"
echo "─────────────────────────────────────"
head -20 "$BLOG_FILE"
echo "..."
echo "─────────────────────────────────────"
echo ""
echo "📊 Blog Post Stats:"
echo "   - Word Count: $(wc -w < "$BLOG_FILE")"
echo "   - Character Count: $(wc -c < "$BLOG_FILE")"
echo "   - Line Count: $(wc -l < "$BLOG_FILE")"
echo ""
echo "🎯 SEO Features Included:"
echo "   ✅ Long-form content (2,500+ words)"
echo "   ✅ Local keywords (Freetown, Sierra Leone)"
echo "   ✅ Product-focused (10 laptops featured)"
echo "   ✅ FAQ section"
echo "   ✅ Clear call-to-actions"
echo "   ✅ Internal linking opportunities"
echo "   ✅ Meta keywords included"
echo ""
echo "📋 Next Steps to Publish:"
echo ""
echo "1. Start your development server:"
echo "   npm run dev"
echo ""
echo "2. Open your browser to:"
echo "   http://localhost:3000/blog/admin"
echo ""
echo "3. Login with admin password:"
echo "   Password: ITServices2025!"
echo ""
echo "4. Copy the content from this file:"
echo "   cat $BLOG_FILE"
echo ""
echo "5. Paste into the blog editor and publish!"
echo ""
echo "🚀 After Publishing:"
echo ""
echo "   → Submit to Google Search Console"
echo "   → Share on Facebook"
echo "   → Post on WhatsApp Business status"
echo "   → Share on Instagram with hashtags:"
echo "     #FreetownBusiness #SierraLeoneTech"
echo "     #LaptopsFreetown #ITServicesFreetown"
echo ""
echo "======================================"
echo "   Ready to publish? Let's go! 🎉"
echo "======================================"
