'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';

type Request = { id: string; customerName: string; email: string; phone: string; deviceType: string; deviceModel?: string; service: string; issueDescription: string; preferredTime?: string; paymentMethod?: string; status: string; technicianNotes?: string; sessionReference?: string; createdAt: string };
const statuses = ['new', 'scheduled', 'in_progress', 'waiting_for_client', 'resolved', 'cancelled'];

export default function RemoteSupportAdminPage() {
  const [items, setItems] = useState<Request[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  useEffect(() => { fetch('/api/remote-support').then(async (response) => { if (!response.ok) throw new Error(); setItems(await response.json()); }).catch(() => setError('Unable to load remote-support requests. Please sign in to the admin area and try again.')).finally(() => setLoading(false)); }, []);
  async function update(id: string, updates: Partial<Request>) { const response = await fetch('/api/remote-support', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, ...updates }) }); if (!response.ok) return alert('Unable to save changes.'); const saved = await response.json(); setItems((current) => current.map((item) => item.id === id ? saved : item)); }
  return <main className="min-h-screen bg-slate-950 p-5 text-white sm:p-8"><div className="mx-auto max-w-6xl"><div className="mb-8 flex items-center justify-between gap-4"><div><p className="text-sm font-bold text-cyan-300">SERVICE DESK</p><h1 className="text-3xl font-black">Remote Support Requests</h1></div><Link href="/admin" className="rounded-lg border border-slate-700 px-4 py-2 text-sm font-bold hover:bg-slate-800">Back to admin</Link></div>{loading ? <p className="text-slate-300">Loading requests…</p> : error ? <p className="rounded-xl bg-red-500/10 p-4 text-red-200">{error}</p> : items.length === 0 ? <p className="rounded-xl border border-slate-800 bg-slate-900 p-8 text-center text-slate-400">No remote-support requests yet.</p> : <div className="space-y-4">{items.map((item) => <article key={item.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><h2 className="text-lg font-bold">{item.customerName}</h2><p className="text-sm text-slate-400">{item.email} · {item.phone} · {new Date(item.createdAt).toLocaleString()}</p></div><select value={item.status} onChange={(event) => update(item.id, { status: event.target.value })} className="rounded-lg border border-slate-700 bg-slate-800 px-3 py-2 text-sm font-bold">{statuses.map((status) => <option key={status}>{status}</option>)}</select></div><div className="mt-4 grid gap-3 text-sm sm:grid-cols-3"><p><span className="text-slate-500">Service:</span> {item.service}</p><p><span className="text-slate-500">Device:</span> {item.deviceType}{item.deviceModel ? ` — ${item.deviceModel}` : ''}</p><p><span className="text-slate-500">Payment:</span> {item.paymentMethod || 'Not selected'}</p></div><p className="mt-4 rounded-lg bg-slate-800 p-3 text-sm text-slate-200">{item.issueDescription}</p><div className="mt-4 grid gap-3 md:grid-cols-2"><input defaultValue={item.sessionReference || ''} onBlur={(event) => update(item.id, { sessionReference: event.target.value })} placeholder="Session reference / support code" className="rounded-lg border border-slate-700 bg-slate-950 p-3 text-sm" /><textarea defaultValue={item.technicianNotes || ''} onBlur={(event) => update(item.id, { technicianNotes: event.target.value })} placeholder="Technician notes" className="min-h-20 rounded-lg border border-slate-700 bg-slate-950 p-3 text-sm" /></div></article>)}</div>}</div></main>;
}
